import fs from "node:fs";
import { NextResponse } from "next/server";
import { imagePath } from "@/lib/paths";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Ctx = { params: Promise<{ id: string }> };

/** Serves infographic PNGs generated by the image model. */
export async function GET(_req: Request, { params }: Ctx) {
  const { id } = await params;

  let file: string;
  try {
    file = imagePath(id);
  } catch {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  if (!fs.existsSync(file)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const bytes = fs.readFileSync(file);
  return new NextResponse(new Uint8Array(bytes), {
    status: 200,
    headers: {
      "content-type": "image/png",
      "content-length": String(bytes.length),
      "cache-control": "private, max-age=31536000, immutable",
    },
  });
}
